version: '3'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: sql12.freesqldatabase.com\sql12647073
      MYSQL_USER: sql12647073
      MYSQL_PASSWORD: hkYAruWkmD
    ports:
      - "3306:3306"